### ISSUE TITLE
Navbar hover animation

### ISSUE THREAD

**Issue by yashksaini-coder** [4darsh-Dev/DecenTrade#10]
Hi 👋🏼 @4darsh-Dev Really good project and front-end is really great. I want to contribute to the Front-End aspect. By giving the navbar better CSS animations.

- [X] I have searched the existing issues.

![image](https://github.com/user-attachments/assets/2fa817af-8812-43b7-9044-37da31eada79)
**Feature Description**  
- Adding CSS animation to make the Front-End look more interactive and makes UI/UX better for the end-users.
- Color transitions: Changing the background or text color on hover.
- Scale animations: Enlarging or shrinking elements slightly when hovered.
- Underline effects: Adding or animating an underline on hover.
- Sliding effects: Elements or borders sliding in when hovered.

**Use Case**  
- Having small light weight animations will make the UI more interactive and make it more engaging with the users.

**Benefits**
- Adding a hover animation to the navbar improves user experience by providing visual feedback, making the interface more interactive, responsive, and intuitive.

**Priority**  
- Medium  

**Record**  
- [X] I agree to follow this project's Code of Conduct (Required)  
- [X] I'm a GSSOC contributor  
- [X] I want to work on this issue  
- [X] I'm willing to provide further clarification or assistance if needed.

---

Can you assign this issue to me @4darsh-Dev as part of the Wob'24 contributor.

**Comment by 4darsh-Dev** [comment]
assigned to you @yashksaini-coder ,
Good issue description...

**Comment by yashksaini-coder** [comment]
@4darsh-Dev I got this when I ran the frontend. Can you help me fix this.
<br>
![image](https://github.com/user-attachments/assets/1ecef7c9-a247-4387-8fd0-9adf28fc5c63)

**Comment by AmanSingh494** [comment]
You have to setup the right file path for the smart contracts compilation details.
To resolve this issue, you have to go through these steps:
1. Navigate to smart-contracts directory.
   `cd smart-contracts`
2. Install the required dependencies using yarn.
    `yarn install` 
3. Compile the smart-contracts.
    `npx hardhat compile`
4. Update the imports in ethereum.js.
    ` import DecentradeNFTAbi from '../../../smart-contracts/artifacts/contracts/Marketplace.sol/DecentradeNFT.json'`
`import DecentradeMarketplaceAbi from '../../../smart-contracts/artifacts/contracts/Marketplace.sol/DecentradeMarketplace.json'
`

These steps would be updated in readme.md in setup section.

**Comment by yashksaini-coder** [comment]
@4darsh-Dev Raised the PR #15 that fix this issue.
