### ISSUE TITLE
[Bug]: FAQ page not visible in dark mode

### ISSUE THREAD

**Issue by AswaniBolisetti** [4darsh-Dev/DecenTrade#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@4darsh-Dev 
In dark mode, the text is not visible properly
So i would like to work on it, could you please assign it to me

### Add ScreenShots

![faqss](https://github.com/user-attachments/assets/e45d5f3a-7855-46c8-a819-ea87e1c216f5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you
@AswaniBolisetti

**Comment by 4darsh-Dev** [comment]
Hey @AswaniBolisetti ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
