### ISSUE TITLE
[Feature Request]: Display Contributor List on Creator Page

### ISSUE THREAD

**Issue by akash70629** [4darsh-Dev/DecenTrade#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To foster a sense of community and attract more developers to contribute to this repository, I propose adding a contributor list to the creator page.

# Now
![image](https://github.com/user-attachments/assets/ad6329b6-8891-470d-bb84-433f2913d5c0)

# It will look like this 
![image](https://github.com/user-attachments/assets/bb7618f9-d2ea-435b-840c-f6f0c3870105)

### Use Case

1. New contributors can see who's involved and reach out for guidance.
2. Existing contributors can track their contributions and feel valued.
3. Project maintainers can easily identify top contributors for collaboration.
4. Users can assess project credibility based on contributor diversity and expertise.

### Benefits

1. Recognize and appreciate existing contributors' efforts.
2. Showcase the project's collaborative nature.
3. Increase project visibility and credibility.
4. Attract new contributors and encourage community growth.
5. Provide a sense of ownership and accountability among contributors.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by akash70629** [comment]
Please assign me this issue with hacktoberfest and gssoc-ext and other tags

**Comment by 4darsh-Dev** [comment]
@akash70629, 
/creators page is for nft creators, 
not contributors of the project, you can create a separate one with ContribPage.jsx

**Comment by 4darsh-Dev** [comment]
Hey @akash70629 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
