### ISSUE TITLE
[Bug]: "Dark/Light Mode Toggle Not Functioning"

### ISSUE THREAD

**Issue by Ankul8471** [4darsh-Dev/DecenTrade#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dark/light mode toggle button does not function as expected. Switching between dark and light modes is unresponsive, and the theme does not change upon toggling.

Steps to Reproduce:

Open the application in any supported browser.
Click on the dark/light mode toggle button.
Observe that the theme does not switch between dark and light modes.
Expected Behavior:
The theme should switch between dark and light modes immediately upon toggling the button.

Environment:

Browser: [Name/Version]
OS: [Operating System]
Device: [Device Details]

### Add ScreenShots

![Screenshot 2024-10-22 001342](https://github.com/user-attachments/assets/79912bae-4f58-438c-854d-231f636d8d9a)

https://github.com/user-attachments/assets/8e34843b-5e6b-4333-a327-2f4d0cc471a1

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
@Ankul8471 
actually our home page is already in kind of dark model
-- check on faq and other pages.

**Comment by 4darsh-Dev** [comment]
how do propose to fix this ?

**Comment by Ankul8471** [comment]
Ok

**Comment by 4darsh-Dev** [comment]
Hey @Ankul8471 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!
