### ISSUE TITLE
[Bug]: mobile view navbar

### ISSUE THREAD

**Issue by jainaryan04** [4darsh-Dev/DecenTrade#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the navbar should have a cross icon to close it
and a hamburger icon to open it

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d20e7963-efd2-4ef7-843b-c5878623bffc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by panwar8279** [comment]
Hi @jainaryan04 , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

**Comment by 4darsh-Dev** [comment]
Hey @jainaryan04 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!
