### ISSUE TITLE
[Bug]: Hover Effect of footer upper section on home page

### ISSUE THREAD

**Issue by roushan-code** [4darsh-Dev/DecenTrade#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
- Footer upper section card is completely attach with footer, and because of that card hover effect is not completely visible.

## Screenshot
![card-hover](https://github.com/user-attachments/assets/35d9a221-e5ab-4d78-bd46-d5d75b00d15c)

## Expected Behaviour
![hover-card-ezgif com-crop](https://github.com/user-attachments/assets/bcbdfbcc-0238-42d9-8518-1171b741e4f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by panwar8279** [comment]
Hi @roushan-code , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

**Comment by roushan-code** [comment]
Hey @panwar8279, Please also add [hacktoberfest](https://github.com/topics/hacktoberfest) lable

**Comment by roushan-code** [comment]
Hey @panwar8279 ,  is there any problem to merge?

**Comment by 4darsh-Dev** [comment]
Hey @roushan-code ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!
