### ISSUE TITLE
[Feature Request]: Addition of Users Forum in FAQs Page and Enhancement of FAQs Page | User Can also Post

### ISSUE THREAD

**Issue by Shariq2003** [4darsh-Dev/DecenTrade#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to enhance the FAQs Page and Add Forums section with Following Functionalities:-

1. Enhance the FAQs Page.
2. Forum Section with Listing of User's Posts in a Grid of Cards with Flip Effect on Cards.
4. User can also Post.
5. Sorting Functionality.
6. Responsive UI.

Please assign this to me under GSSOC Ext.

### Use Case

.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
good idea @Shariq2003, 
assigend to you

**Comment by sharanikaa** [comment]
Please assign this issue to me. I am willing be working on this.

**Comment by 4darsh-Dev** [comment]
Hey @Shariq2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
