### ISSUE TITLE
[Bug] [URGENT]: Footer Section Occur Twice in Creators Page

### ISSUE THREAD

**Issue by Shariq2003** [4darsh-Dev/DecenTrade#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/1e772a3a-15f6-4540-a62f-8a056f68875c

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
check it again : https://decentrade.vercel.app/creators
i think it's fixed by someone already

**Comment by 4darsh-Dev** [comment]
Hey @Shariq2003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!
