### ISSUE TITLE
[Feature Request]: [Add Multi-Language Support for Global Accessibility]

### ISSUE THREAD

**Issue by sezallagwal** [4darsh-Dev/DecenTrade#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement multi-language support , allowing users from different regions to interact with the website in their preferred language. This feature will enhance accessibility and usability, making it easier for non-English-speaking users to browse the site.

### Use Case

Set up a language selection dropdown or toggle in the header/footer for easy switching.
Store language preferences using cookies or local storage.
Ensure that the translated content adapts dynamically based on the selected language.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @sezallagwal , 
how you are thinking to implement it ?

**Comment by sezallagwal** [comment]
> assigned to you @sezallagwal , 
> how you are thinking to implement it ? 

I'm gonna use google translator

**Comment by 4darsh-Dev** [comment]
Hey @sezallagwal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!
