### ISSUE TITLE
[Bug]: Not taking to  correct pages

### ISSUE THREAD

**Issue by Garima-149** [4darsh-Dev/DecenTrade#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the added screenshot,those 3 sections which are faking to provide leverage of working of 3 buttons even after pages are available,need some attention. @4darsh-Dev please assign me this issue under hacktoberfest'2024.I am willing to work upon.

Solution -
Linking the buttons with their appropriate path.

### Add ScreenShots

![Screenshot (155)](https://github.com/user-attachments/assets/60ce5d85-eb5f-44fb-be87-2a02b4ef00bb)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Garima-149** [comment]
@4darsh-Dev please assign this to me

**Comment by panwar8279** [comment]
Hi @Garima-149 , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

**Comment by Garima-149** [comment]
@panwar8279 @4darsh-Dev 
The deployment link of website is crashed and also project on local host is not working.Please guide?
![Screenshot (158)](https://github.com/user-attachments/assets/1a9695c8-07d9-40ae-8521-1ecf6953a4b9)

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
