### ISSUE TITLE
[Feature Request]: Adding css to existing scrollbar

### ISSUE THREAD

**Issue by Garima-149** [4darsh-Dev/DecenTrade#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@4darsh-Dev Existing scrollbar is very simple and normal. It can be more attractive by adding some css to it.Adding CSS to it will enhance its UI. 
Please assign this issue to me under  hacktoberfest'24.

### Use Case

Enhancing UI

### Benefits

![Screenshot (155)](https://github.com/user-attachments/assets/dc174377-6a24-45bb-a3de-f8f67fa14579)

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Garima-149** [comment]
@4darsh-Dev please assign this to me

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
