### ISSUE TITLE
Switch IPFS Provider from Infura to Pinata Due to Usage Limitations

### ISSUE THREAD

**Issue by AmanSingh494** [4darsh-Dev/DecenTrade#14]
# Issue Summary
Infura is limiting IPFS usage, which is going to affect the functionality of the app. This issue proposes switching from Infura to Pinata which is providing good IPFS services.

## Problem
Currently, the application uses Infura for IPFS, but Infura has recently imposed limits on its IPFS users, which has impacted the app's ability to upload and retrieve files efficiently. As a result, users may experience disruptions in IPFS functionality.

### Proposed Solution
Switch from Infura to Pinata for IPFS services. Pinata provides robust IPFS services with fewer limitations, ensuring better availability and reliability. Here’s how the migration could be handled:

1. Update the IPFS-related code to use Pinata’s API.
2. Ensure Pinata keys and configurations are securely stored and accessed by the app.
3. Test the new integration to verify that all file uploads and retrievals work as expected.
### Steps to Implement
1. Create a Pinata account and generate API keys.
2. Replace Infura’s IPFS endpoints with Pinata's API endpoints in the codebase.
3. Update the environment variables to securely store Pinata’s API keys.
4. Test the application’s IPFS functionality with Pinata.

@4darsh-Dev Please assign this issue to me as a Wob'24 contributor.

**Comment by 4darsh-Dev** [comment]
sure @AmanSingh494, 
assigned to you...

**Comment by 4darsh-Dev** [comment]
Hey @AmanSingh494 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by AmanSingh494** [comment]
You are welcome and Thanks to you too for giving me the opportunity to contribute to this project @4darsh-Dev. Looking forward to make more good contributions!!

> Hey @AmanSingh494 ! Thank you so much for your raising the issue💗 It’s all yours, you can come anytime again and make some contributions! 🚀 Alone, we can do little, but together we can do so much! 😇

**Comment by AmanSingh494** [comment]
@4darsh-Dev Please add hacktoberfest label too as I have participated in that too.
