### ISSUE TITLE
Navbar Elements Are Misaligned

### ISSUE THREAD

**Issue by sezallagwal** [4darsh-Dev/DecenTrade#145]
![image](https://github.com/user-attachments/assets/56e2760a-38cc-4829-9f84-d5ed88fedc94)

**Description:**
The elements in the navbar are not properly aligned, leading to distorted spacing and inconsistent positioning. Specifically:
- Some items appear vertically misaligned, causing the layout to look uneven.
- The issue is noticeable across different screen resolutions, suggesting a lack of responsive alignment.

**Steps to Reproduce:**
1. Open the website and navigate to the homepage.
2. Observe the navbar elements (e.g., logo, links, search bar, buttons) across different screen sizes.
3. Notice the misalignment, especially between the text elements and buttons.

**Expected Behavior:**
All elements in the navbar should be horizontally aligned on the same line with consistent spacing.

**Actual Behavior:**
The elements appear distorted, with some items not lining up correctly.

**Suggested Solution:**
- Review the CSS styling for the navbar, particularly `display`, `align-items`, and `margin` properties.
- Ensure the elements are placed within a flex container with proper alignment settings.
- Test across different screen sizes for a responsive layout.

**Comment by panwar8279** [comment]
Hi @sezallagwal , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

**Comment by sezallagwal** [comment]
> Hi @sezallagwal , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

ok will do

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @sezallagwal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
