### ISSUE TITLE
Add Hover Effects to Footer Links

### ISSUE THREAD

**Issue by sezallagwal** [4darsh-Dev/DecenTrade#146]
![image](https://github.com/user-attachments/assets/943df1fe-a026-4554-b442-bf0b6ded5717)
**Description:**
The footer links currently do not have any hover effects, making the user experience less interactive. Adding hover effects to the links will improve the visual feedback and overall aesthetics.

**Steps to Reproduce:**
1. Scroll down to the footer section on the website.
2. Hover over any of the footer links (e.g., Quick Links, Community, etc.).
3. Notice that there is no visual indication when hovering over the links.

**Expected Behavior:**
Footer links should have a hover effect, such as changing color, underlining, or adding an animation, to provide feedback when users interact with them.

**Actual Behavior:**
There is no visual feedback when hovering over the footer links.

**Suggested Solution:**
- Add a CSS hover effect to the footer links, such as:
  - Changing the text color.
  - Adding an underline or background effect.
  - Adding a transition for smooth animation.

**Additional Notes:**
Consider ensuring the hover effects match the overall theme and design of the website for a consistent user experience.

**Comment by panwar8279** [comment]
Someone already working on it.

**Comment by 4darsh-Dev** [comment]
Hey @sezallagwal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
