### ISSUE TITLE
[Bug]: Only One FAQ Item Should Remain Open at a Time

### ISSUE THREAD

**Issue by sezallagwal** [4darsh-Dev/DecenTrade#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When opening a new FAQ, the previously opened FAQ item does not close automatically. This causes multiple FAQ items to stay open simultaneously, which affects the user experience and can lead to a cluttered view. I want to Implement functionality to automatically close the previously opened FAQ item whenever a new one is opened.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b40e276c-f93e-4241-b271-3b3cb60ffea6)
please assign this to me under `hacktoberfest` and `gssoc-ext` @visheshrwl

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by panwar8279** [comment]
Hi @sezallagwal , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

**Comment by sezallagwal** [comment]
ok will do

> Hi @sezallagwal , I have assigned this task to you. Kindly complete within 2 days. Also add a 30 sec demo video. Good luck!

**Comment by panwar8279** [comment]
Already done

**Comment by 4darsh-Dev** [comment]
Hey @sezallagwal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
