### ISSUE TITLE
[Feature Request]: Enhancement in FAQ's Section

### ISSUE THREAD

**Issue by dipalichourasia** [4darsh-Dev/DecenTrade#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to work on FAQ's page. At present the page look very simple. I want to add some CSS property to make this page more attractive.
Please Assign me this issue.
Before Changes
<img width="949" alt="Before FAQ" src="https://github.com/user-attachments/assets/5f2e6de1-6368-4ece-a037-ebdf2cd26bf2">

Note:
1) I am GSSoC 24 Extended Contributor
2) Please add label of gssoc ext & level for this issue.

### Use Case

It looks more attractive.

### Benefits

User attraction

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @dipalichourasia , 
As our website got recent updates, have a look and propose your changes first before raising pr.

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @dipalichourasia ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
