### ISSUE TITLE
[Documentation Update]: Add Contributing.md

### ISSUE THREAD

**Issue by Devaki01** [4darsh-Dev/DecenTrade#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Contributing.md file is empty right now.

### Suggested Change

I would love to contribute by adding relevant content to CONTRIBUTING.md which includes guidelines for reporting issues, making feature requests, setting up project, committing changes, submitting code, updating documentation, and following the pull request process.

### Rationale

A well-structured CONTRIBUTING.md would ensure consistency in code quality and collaboration and help beginners contribute better.

Please assign me this issue under ggosc'24 and wob. 

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
already exists

**Comment by 4darsh-Dev** [comment]
Hey @Devaki01 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
