### ISSUE TITLE
[Documentation Update]: adding docker file

### ISSUE THREAD

**Issue by Hamza1821** [4darsh-Dev/DecenTrade#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

i want to add a dockerfile for containerization

### Suggested Change

pls assign this to me under gssoc-ext

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @Hamza1821, 
Ensure testing it properly to avoid any issues, 
u can test on platforms like render .. etc

**Comment by 4darsh-Dev** [comment]
Hey @Hamza1821 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
