### ISSUE TITLE
[Bug]: Copyright and social links are not properly visible in footer

### ISSUE THREAD

**Issue by Hamza1821** [4darsh-Dev/DecenTrade#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**when scroll down to footer we are unable to view copyright and social link properly because language change button and chat button covers them**

assign this to me under gssoc-ext

### Add ScreenShots

![Screenshot 2024-11-03 at 12-45-07 DecenTrade NFT Marketplace](https://github.com/user-attachments/assets/032344d4-68bd-441f-8c55-8b4bfc4cf085)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
Hey @Hamza1821 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
