### ISSUE TITLE
[Feature Request] :  Adding separate contact us section in FAQ's

### ISSUE THREAD

**Issue by AbhijitMotekar99** [4darsh-Dev/DecenTrade#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a dedicated "Contact Us" section within the FAQ page, enabling users to easily reach out for support, inquiries, or further assistance beyond the FAQ content. This section would provide users with options to contact support via various channels (e.g., email, phone, live chat) and include a contact form for submitting specific questions or feedback.

### Use Case

When users go through the FAQ page and don’t find answers to their specific questions, they can quickly access the "Contact Us" section to get personalized assistance. This feature could be particularly helpful for:

- Users who need direct support for specific issues not covered in the FAQ.
- Visitors interested in providing feedback on the FAQs or other aspects of the project.
- Potential collaborators or clients looking for more information and an easy way to reach out.

### Benefits

- Enhanced User Experience: Makes it easier for users to seek help directly from the FAQ page without navigating away.
- Increased Engagement: Encourages users to reach out and engage, reducing the chances of users abandoning the site if they don’t find what they need in the FAQs.
- Better Feedback Collection: The form can be a valuable source of feedback for improving FAQs, understanding common questions, and enhancing support.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @AbhijitMotekar99, 
Share design previews and make significant contrib to get good levels

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @AbhijitMotekar99 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
