### ISSUE TITLE
[Feature Request] : Adding Scroll to top button

### ISSUE THREAD

**Issue by AbhijitMotekar99** [4darsh-Dev/DecenTrade#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a "Scroll to Top" button that appears on the page when the user scrolls down a certain distance. This button will allow users to quickly return to the top of the page with a single click. It could be positioned in the lower right corner of the page, styled minimally to avoid distraction but remain accessible and visible.

### Use Case

When users browse through long pages, such as documentation, blogs, or detailed FAQ sections, scrolling back to the top can be tedious. This feature would be beneficial in the following scenarios:

- Users reaching the bottom of a lengthy page and needing to access the top-level navigation or search.
- Users wishing to quickly revisit the start of content after reading through a page.

### Benefits

- Improved User Experience: Enhances site navigation, especially for pages with extensive content, reducing the need for excessive scrolling.
- Increased Accessibility: Helps users with limited mobility or those using mobile devices where scrolling can be more cumbersome.
- Professional UI Design: Adds a polished touch to the interface, as scroll-to-top buttons are a common feature on well-designed sites, contributing to a better overall user impression.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
Hey @AbhijitMotekar99 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
