### ISSUE TITLE
Fixing the connect wallet part

### ISSUE THREAD

**Issue by ayush-848** [4darsh-Dev/DecenTrade#17]
![image](https://github.com/user-attachments/assets/9e7019c9-13fc-4bff-96d3-42a52473d7a4)

**Comment by ayush-848** [comment]
@4darsh-Dev please assign this issue to me

**Comment by 4darsh-Dev** [comment]
assigned to you @ayush-848 , 
propose your changes first, 
how you want to change them ...

**Comment by ayush-848** [comment]
@4darsh-Dev 
![image](https://github.com/user-attachments/assets/71cd9817-5d29-4feb-b9fb-c21a5a0c8f2f)
i was talking like this

**Comment by 4darsh-Dev** [comment]
i think it would be better to change the github button on top right corner to connect wallet , 
and use a github icon only as separate one, position left to the search bar
@ayush-848

**Comment by 4darsh-Dev** [comment]
also connect your meta mask wallet once , 
this will help you to understand the changes better.

**Comment by ayush-848** [comment]
@4darsh-Dev I dont have any NFT knowledge
I connected with metamask
![image](https://github.com/user-attachments/assets/8ccd0693-fd5a-4aa6-96a4-6c02deab1644)
it is showing like this

**Comment by 4darsh-Dev** [comment]
okay no problem, 
just adjust the wallet button in place of github button and as told in above conversation, 
only,
we'll fix the remain part..

**Comment by ayush-848** [comment]
> okay no problem, just adjust the wallet button in place of github button and as told in above conversation, only, we'll fix the remain part..

@4darsh-Dev should i only keep the Connect Wallet button

**Comment by ayush-848** [comment]
> > okay no problem, just adjust the wallet button in place of github button and as told in above conversation, only, we'll fix the remain part..
> 
> @4darsh-Dev should i only keep the Connect Wallet button and remove the texts around it

@4darsh-Dev ??

**Comment by 4darsh-Dev** [comment]
@ayush-848 , 
adjust it such that first it looks like connect wallet button, and when connected it turns green and the text changes to wallet connected and remove else part ..

**Comment by 4darsh-Dev** [comment]
@ayush-848  any updates??

**Comment by ayush-848** [comment]
@4darsh-Dev I was able to do the button part but the some backend problems are are there. I will try again in the evening

**Comment by 4darsh-Dev** [comment]
okay @ayush-848

**Comment by 4darsh-Dev** [comment]
Hey @ayush-848 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
