### ISSUE TITLE
[Feature Request]: Re-design creators page 

### ISSUE THREAD

**Issue by Son7c** [4darsh-Dev/DecenTrade#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would redesign the contributors page and make it attractive and also i will add cool hovering animations over contributors cards like below

https://github.com/user-attachments/assets/5293a96c-ede6-48d0-a5b9-7c446b68fd31

### Use Case

Enhances UI

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Son7c** [comment]
@4darsh-Dev Please assign me this issue under gssoc

**Comment by 4darsh-Dev** [comment]
assigned to u @Son7c , 
Go through contrib guidelines, 
nd make sure to follow code architecture

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @Son7c ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
