### ISSUE TITLE
[Feature Request]: Add hover effect to the socialmedia icons on the footer

### ISSUE THREAD

**Issue by Richajaishwal0** [4darsh-Dev/DecenTrade#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the hover effect on the social media icons of twitter,facebook and instagram.

### Use Case

It can be more engaging for the users as it provides visual feedback.

### Benefits

It will make the website more interactive

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Vigneshwaran-01** [comment]
Hi! I’d like to work on this issue if no one else has claimed it yet.

**Comment by 4darsh-Dev** [comment]
@Richajaishwal0 
it's a very minor change, 
U cant get levels for just hover effect

**Comment by Richajaishwal0** [comment]
@4darsh-Dev  I had got label 1 for the similar changes in other repos.  Please assign atleast label 1. Thank you

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!

**Comment by 4darsh-Dev** [comment]
Hey @Richajaishwal0 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
