### ISSUE TITLE
[Documentation Update]: Want to add security policy 

### ISSUE THREAD

**Issue by Dipanita45** [4darsh-Dev/DecenTrade#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Want to add security policy to protect the website against the harms and no-one can misuse 

### Suggested Change

Add security policy to the website 

### Urgency

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Dipanita45** [comment]
Please assign me this issue 
@4darsh-Dev

**Comment by 4darsh-Dev** [comment]
okay @Dipanita45 , 
assigned to you

**Comment by 4darsh-Dev** [comment]
Hey @Dipanita45 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!
