### ISSUE TITLE
[Feature Request]: Clickable Logo in the Navbar

### ISSUE THREAD

**Issue by abhishekpaturkar** [4darsh-Dev/DecenTrade#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Can we make the logo which is in the navbar clickable to refresh the page or re-direct to the home page?
![Capture](https://github.com/user-attachments/assets/a0551e5e-f0d1-4586-ab4d-d4cc27ed624b)

### Use Case

Help use to refresh the page

### Benefits

Enhancement in the user experience

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
this is a very minor change @abhishekpaturkar , 
how should I assign the labels to it.

**Comment by panwar8279** [comment]
I have assigned this task to you. Kindly complete within 2 days and also add a 10 to 30sec demo video. Good luck!

**Comment by panwar8279** [comment]
Alr

**Comment by 4darsh-Dev** [comment]
Hey @abhishekpaturkar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
