### ISSUE TITLE
[Feature Request]: FAQPage for website

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/DecenTrade#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Create a well designed FAQs page for the website,
I have already added the routes.
Make sure that page follows home page design patterns

### Use Case

1. contains all the frequently asked questions for creators and buyers
: you can take reference from different marketplaces for questions and answers.

### Benefits

Better guidance and help will be provided to visitors regarding common doubts.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Dharmi-dev** [comment]
i am very excited to solve this issue with you
i have little prior experience of Girl Summer Script Of Code
Please assign this issue to me

**Comment by 4darsh-Dev** [comment]
tujhe nahi milega ?

**Comment by HemantBatra873** [comment]
If its still avaialble , assign it to me I'll do it within 48 hours . @4darsh-Dev

**Comment by Dharmi-dev** [comment]
![Screenshot 2024-10-18 125945](https://github.com/user-attachments/assets/2d1ed555-b9a7-4cb4-9f61-6a5bbb19c700)

This is just a preview , also I will make sure to matching with the theme of the website

**Comment by 4darsh-Dev** [comment]
@Dharmi-dev 
you should close issue after your PR is merged .

**Comment by 4darsh-Dev** [comment]
Hey @4darsh-Dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
