### ISSUE TITLE
404 Error Page is Missing

### ISSUE THREAD

**Issue by PratikMane0112** [4darsh-Dev/DecenTrade#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Issue : In the current situation of project, if user hits  invalid URL then website is missing with 404 error page to render them back to homepage.

- Screenshot : 

![Screenshot 2024-10-01 200524](https://github.com/user-attachments/assets/a7e3117e-9303-45a9-8b01-4bd176e4c166)

### Use Case

Good user experience for invalid URL.

## Work to do : 

- I will add a appropriate a 404 error page which matches with the website background.
- I will start working after assigning the issue & complete it in 2 days.

### Benefits

Redirect to home page if any invalid URL requested from user.

## Request for contribution :

- Please, assign me this task under wob24 & gssoc-ext

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @PratikMane0112 , 
Share the design preview SS, 
make a page in /pages with name NotFoundPage.jsx 
and make components in /components, 
Follow the code architecture :

**Comment by nancy-gupta123** [comment]
Hello! I'd like to work on this issue. Could you please assign it to me

**Comment by 4darsh-Dev** [comment]
Hey @PratikMane0112 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
