### ISSUE TITLE
[Feature Request]: Add Connect Wallet functionality

### ISSUE THREAD

**Issue by rudrapratap63** [4darsh-Dev/DecenTrade#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We would like to implement a "Connect Wallet" feature to enable users to link their cryptocurrency wallets to the application. This functionality will enhance user experience by allowing seamless transactions and interactions within the platform.

### Use Case

-  Users can easily access their wallets without needing to input their wallet addresses manually.
- Simplifying wallet connection may encourage more users to participate in transactions.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by rudrapratap63** [comment]
@4darsh-Dev please assign this issue to me and also add gssoc-ext, hacktoberfest and level3 label on it.

**Comment by 4darsh-Dev** [comment]
@rudrapratap63 , 
but it is already in the page : 
have a look --> https://decentrade.vercel.app/
any other changes u like to make

**Comment by rudrapratap63** [comment]
@4darsh-Dev Yes, it's already on the page, but when we click "Connect Wallet," it does not connect to the crypto wallet. Could you please look into this issue? Let me know if you need any additional details from my side.

**Comment by 4darsh-Dev** [comment]
which wallet you're using ..

**Comment by rudrapratap63** [comment]
@4darsh-Dev I apologize for the inconvenience, there is an issue from my adblocker

**Comment by 4darsh-Dev** [comment]
ok no problem, 
Find more issues/ enhancements 👍🏻

**Comment by rudrapratap63** [comment]
@4darsh-Dev okk sir and sir if you have any issue for me ?

**Comment by 4darsh-Dev** [comment]
@rudrapratap63 
you can raise an issue for making home page and navbars responsive,  
across various devices with different widths,  ( mobile, iPad ) with CSS media queries, 
and for footer as well 
You'll get either level 2 or 3 on this ...

**Comment by 4darsh-Dev** [comment]
Hey @rudrapratap63 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
