### ISSUE TITLE
[Feature Request]:  Light/Dark Mode Toggle Button

### ISSUE THREAD

**Issue by Priyanshu282003** [4darsh-Dev/DecenTrade#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This update introduces a new feature that allows users to switch between light and dark modes seamlessly. The toggle button enhances user experience by providing a visually comfortable environment suitable for different lighting conditions.

### Use Case

The light/dark mode toggle button enhances user experience by allowing individuals to choose their preferred visual interface, reducing eye strain in low-light conditions and catering to personal preferences. This feature improves accessibility for users with visual impairments and adheres to standards, ensuring a wider audience can use the application. By saving user preferences in local storage, the application maintains consistency across sessions, fostering personalization and increasing user retention. The modern aesthetic of dark mode aligns with current design trends, making the project visually appealing and adaptable to various environments. Overall, this feature promotes user satisfaction and encourages continued engagement with the application.

### Benefits

The light/dark mode toggle button brings numerous benefits to the project and its community by enhancing user experience and accessibility. Users can customize their interface to reduce eye strain in varying lighting conditions, promoting longer usage without discomfort. This personalization fosters a sense of ownership, leading to higher user retention and continued engagement. Additionally, the feature accommodates users with visual impairments, making the application more inclusive. By aligning with modern design trends, it keeps the project visually appealing and relevant, while also encouraging community feedback and collaboration for further enhancements. Overall, this feature significantly improves usability and community involvement.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @Priyanshu282003 
Let me know if you need any help

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by Sourabh782** [comment]
hey @4darsh-Dev can i work on this issue?

**Comment by 4darsh-Dev** [comment]
This feature has been already added in the website,

**Comment by 4darsh-Dev** [comment]
Hey @Priyanshu282003 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
