### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [4darsh-Dev/DecenTrade#4]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by Ishitagu** [comment]
Hi! I would like to contribute to this issue, would really appreciate it if u assign it to me.

**Comment by Sibam-Paul** [comment]
@4darsh-Dev Please assign me this issue as i wanna work under wob'24

**Comment by 4darsh-Dev** [comment]
@anusha7530 , 
issues are on FCFS (first come first serve) basis right ?

**Comment by 4darsh-Dev** [comment]
Hey @anusha7530 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
