### ISSUE TITLE
[Feature Request]: Redesign Request: Create NFT Page Layout

### ISSUE THREAD

**Issue by saadgibawa** [4darsh-Dev/DecenTrade#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to propose a redesign of the Create NFT page to improve its visual appeal and user experience. The current layout is functional, but a redesign could make the page more intuitive and engaging for users.

### Use Case

This redesign would improve user experience by making the Create NFT page more user-friendly and visually appealing. A cleaner layout and better functionality, like drag-and-drop file upload and improved form design, would streamline the process of creating NFTs, making it more efficient and enjoyable.

### Benefits

This feature would enhance the project's overall user experience by making the **Create NFT** process more intuitive and accessible. A modern, visually appealing design could attract more users, increase engagement, and encourage more NFT creations. It would also provide a smoother and more efficient workflow, benefiting both new and experienced users.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
@saadgibawa 
assigned to you, 
share design preview or SS / link before starting you work

**Comment by 4darsh-Dev** [comment]
Hey @saadgibawa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by saadgibawa** [comment]
Hi @4darsh-Dev Thanks! and i have also raised a PR resloving the footer redirect links issue that you assigned to me but you havent reviewed it yet. Please do review the PR and let me know if any further changes are required.
Here is the PR link: https://github.com/4darsh-Dev/DecenTrade/pull/71
