### ISSUE TITLE
[Feature Request]: Add animated cursor

### ISSUE THREAD

**Issue by krishpathak** [4darsh-Dev/DecenTrade#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add an animated cursor please look at the video for reference 

https://github.com/user-attachments/assets/10d6b722-e81a-42d7-9cc5-ed366e6177dc

### Use Case

For better UI.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by krishpathak** [comment]
@4darsh-Dev  assign me issue with tag gssoc and hacktober

**Comment by 4darsh-Dev** [comment]
nice @krishpathak ,
assigned to you.

**Comment by krishpathak** [comment]
Please assign me level @4darsh-Dev

**Comment by 4darsh-Dev** [comment]
Hey @krishpathak ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
