### ISSUE TITLE
[Feature Request]: Adding Of Contributing.md 

### ISSUE THREAD

**Issue by milansamuel609** [4darsh-Dev/DecenTrade#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The contributing.md file is not present and it may cause some confusions and problems to the contributors while contributing.

### Use Case

Adding it will make the contribution easier for the contributors. Also it will help them understand all the correct coding practices. Please can you assign me this issue. I will ensure that I will do my best. Please also add gssoc extend label.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
okay @milansamuel609 , 
assigned to you,

**Comment by milansamuel609** [comment]
> okay @milansamuel609 , assigned to you,

Thank you so much for this opportunity. I will give my best and create a good Contributing.md

**Comment by 4darsh-Dev** [comment]
Hey @milansamuel609 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by milansamuel609** [comment]
> Hey @milansamuel609 ! Thank you so much for your raising the issue💗 It’s all yours, you can come anytime again and make some contributions! 🚀 Alone, we can do little, but together we can do so much! 😇

Thank you so much for the appreciation.
