### ISSUE TITLE
Improve card design on the home page 

### ISSUE THREAD

**Issue by shubhagarwal1** [4darsh-Dev/DecenTrade#48]
<img width="1282" alt="Screenshot 2024-10-17 at 6 17 38 PM" src="https://github.com/user-attachments/assets/8c1a40f4-8da8-4a9c-8a06-5721de154c07">

**Comment by panwar8279** [comment]
Hi @shubhagarwal1 , I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by 4darsh-Dev** [comment]
Hey @shubhagarwal1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
