### ISSUE TITLE
Make the navbar sticky 

### ISSUE THREAD

**Issue by shubhagarwal1** [4darsh-Dev/DecenTrade#49]
<img width="1440" alt="Screenshot 2024-10-17 at 6 18 08 PM" src="https://github.com/user-attachments/assets/dd6f28b5-8b56-422c-9fe4-4af913151f81">

**Comment by panwar8279** [comment]
Hi @shubhagarwal1 , I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by 4darsh-Dev** [comment]
Hey @shubhagarwal1 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
