### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by anusha7530** [4darsh-Dev/DecenTrade#5]
As the maintainer of a collaborative repository, it's essential to keep Issues up-to-date to help the student community understand how they can contribute. By creating a mix of issues, from simple tasks like updating documentation to more complex ones like developing new features, you can cater to contributors of all skill levels. The more actively you engage, the more chances there are for meaningful collaboration.

**Recommendations:**
- Regularly create issues of varying difficulty and label them accordingly:  wob24, Level 1, Level 2, Level 3 etc.
- Scoring for the leaderboard is as follows:
   - Each PR earns one point.
   - Level 1 Issues: 10 points.
   - Level 2 Issues: 25 points.
   - Level 3 Issues: 45 points.
- Include documentation-related issues to provide an easier entry point for beginners to explore open-source.
- Even if you plan on solving an issue yourself, generate it to maintain the repository’s activity.
- Commit and contribute frequently to prevent the repo from becoming inactive.

Reference: https://github.com/Durgesh4993/CryptoX/issues

**Comment by 4darsh-Dev** [comment]
Thanks @anusha7530 for sharing the Info

**Comment by 4darsh-Dev** [comment]
@anusha7530 can you confirm, 
whether Level 1 --> L is capital or small

**Comment by 4darsh-Dev** [comment]
Hey @anusha7530 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Hey @anusha7530 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
