### ISSUE TITLE
[BUG]: Create NFT Form UI Is Inconsistent

### ISSUE THREAD

**Issue by PrityanshuSingh** [4darsh-Dev/DecenTrade#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The UI of the Create NFT form is not consistent with the rest of the website's theme. The form's design, including button styles, does not match the overall look and feel of the site, resulting in a disjointed appearance. The Create NFT form should have a consistent design with the rest of the website, including matching button styles that align with the theme.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e0b30a73-260e-41bf-a905-e12683c622a2)

Please assign this issue to me under gssoc-ext level2, wob24 and hactoberfest-accecpted, @4darsh-Dev  , as I am interested in working on it.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by panwar8279** [comment]
Hi @PrityanshuSingh , I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by PrityanshuSingh** [comment]
Hi @panwar8279 , I have opened a PR for the same issue. #67

**Comment by 4darsh-Dev** [comment]
Hey @PrityanshuSingh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
