### ISSUE TITLE
[Feature Request]: Wallet intergration

### ISSUE THREAD

**Issue by Boobeshkumar56** [4darsh-Dev/DecenTrade#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i would like to integrate metamask wallet to the connect wallet option

### Use Case

i would increase the functionality of the app and make easy to use and increase the security could you please assign this under hacktoberfest and wob24 and i would like to give level 2 lable for this

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
Hey @Boobeshkumar56 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
