### ISSUE TITLE
[Feature Request]: Add a toggle for the navbar on small devices

### ISSUE THREAD

**Issue by saurabh-dev-vns** [4darsh-Dev/DecenTrade#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Add a toggle for the navbar on small devices" feature allows the website's navigation bar to collapse into a toggleable menu when viewed on smaller devices, such as smartphones and tablets. Instead of displaying the full navigation menu, a button (commonly represented by a hamburger icon) will appear. When clicked, the button will reveal or hide the menu items, providing a cleaner and more user-friendly interface on smaller screens.

### Use Case

 a toggle feature ensures the content remains the focus while still offering easy access to navigation options.

### Benefits

- Improved User Experience.
- Responsive Design.
- Space Optimization.
- Faster Navigation.
- Enhanced Aesthetic Appeal.
- 

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by saurabh-dev-vns** [comment]
@panwar8279, please assign this issue to me and also label it as gssoc-ext.

**Comment by 4darsh-Dev** [comment]
Hey @saurabh-dev-vns ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
