### ISSUE TITLE
[Feature Request]: Add Chatbot for User Assistance and Transaction Support on DecenTrade

### ISSUE THREAD

**Issue by amanver45** [4darsh-Dev/DecenTrade#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We would like to add a chatbot to DecenTrade, a decentralized digital marketplace, to enhance user experience and provide real-time assistance. The chatbot will be integrated into the existing platform to help users with queries related to digital asset transactions, account management, and general support.

### Use Case

the chatbot will be beneficial in the following scenario:

User Onboarding: New users often need guidance in navigating decentralized platforms. The chatbot can assist them in understanding how to connect their Ethereum wallets, browse digital assets, and make secure transactions.
Transaction Queries: Users can ask about the status of their transactions, details of their purchases, and potential errors during smart contract interactions.
General FAQs: Users can ask questions about the platform, its features, and how to resolve common issues without needing to contact support

### Benefits

Improved User Experience: The chatbot will offer real-time assistance, reducing user frustration and helping them complete tasks faster.
Reduced Support Load: Common queries can be handled automatically by the bot, reducing the need for human intervention and freeing up resources for more complex issues.
Increased User Engagement: A chatbot creates a more interactive experience, keeping users engaged and helping them complete transactions seamlessly.
Scalability: As the user base of DecenTrade grows, the chatbot will be a scalable solution to handle increased support and transaction-related questions.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @amanver45, 
Propose your design for the chatbot UI interface, 
Go through contributing guidelines

**Comment by 4darsh-Dev** [comment]
Hey @amanver45 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
