### ISSUE TITLE
[Bug]: Error handling at explore page

### ISSUE THREAD

**Issue by IkkiOcean** [4darsh-Dev/DecenTrade#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When navigating to the explore page, if the user's wallet is not found, the application continues to load indefinitely without showing an error message. There is no proper error handling in place, which leads to a poor user experience as users are left waiting without any feedback.

**Current Behavior:**
- If the application fails to detect or connect a wallet on the explore page, it continues loading indefinitely.
- There is no feedback or error message displayed to the user.
- No error handling mechanism is in place to stop the loading process and notify the user of the wallet issue.

**Expected Behavior:**
- If the wallet is not found, an appropriate error message should be displayed.
- The loading spinner should stop, and the user should be notified of the issue.
- Error handling should be implemented to manage cases where the wallet is not detected or fails to connect.

**Steps to Reproduce:**
1. Navigate to the explore page without a connected wallet or with an unsupported wallet.
2. Observe the loading spinner continuing indefinitely without any error message.

**Proposed Solution:**
1. Implement error handling for the "Wallet Not Found" case.
   - If the wallet is not detected, display a clear error message like: `Wallet not found. Please connect a valid wallet to explore items.`
2. Stop the loading spinner when the error occurs to avoid infinite loading.
3. Ensure proper fallback behavior so the user can try reconnecting or return to a previous state.

### Add ScreenShots

<img width="1280" alt="Screenshot 2024-10-20 at 2 10 52 PM" src="https://github.com/user-attachments/assets/8c696899-995c-458d-b39a-52804dcb3c03">

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 4darsh-Dev** [comment]
assigned to you @IkkiOcean, 
We've updated our project setup recent 
visit : https://decentrade.vercel.app/
### Try creating a nft to check the feature

**Comment by IkkiOcean** [comment]
> assigned to you @IkkiOcean, We've updated our project setup recent visit : https://decentrade.vercel.app/
> 
> ### Try creating a nft to check the feature

I tried creating not but the create button didnt work..

**Comment by IkkiOcean** [comment]
@4darsh-Dev while working on explore page, I also notice that similar errors are also present on create NFT page so I will be handling them also. We need to implement a check for where the user has connected their wallet to not.

<img width="1280" alt="Screenshot 2024-10-20 at 10 45 57 PM" src="https://github.com/user-attachments/assets/fb558f25-d45d-46af-88cf-ab74397c04ed">

**Comment by 4darsh-Dev** [comment]
@IkkiOcean 
you need to  use metmask or any web3 wallet for adding nfts
-- currently we're using Ethereum sepolia test net 
-- you can use this feature after adding faucets from chainlink

**Comment by IkkiOcean** [comment]
@4darsh-Dev okay. well I dont have much experience in web3 but I did added the error handling in the explore page so do look at it.

**Comment by 4darsh-Dev** [comment]
Hey @IkkiOcean ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
