### ISSUE TITLE
[Bug]: Footer missing at Create NFT page and Items are overflowing

### ISSUE THREAD

**Issue by IkkiOcean** [4darsh-Dev/DecenTrade#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the "Create NFT" page, the footer is missing, and the items of the footer are overflowing beyond their container. This causes layout issues and affects the overall user experience, especially on smaller screens.

**Current Behavior:**
- The footer is not visible on the Create NFT page, which disrupts the consistency of the application’s layout.
- Item within the footer are overflowing their containers, causing visual distortion and misalignment.
- 
**Expected Behavior:**
- The footer should be visible and properly positioned at the bottom of the Create NFT page.
- Items should be properly contained within their respective elements, with no overflow or misalignment issues.
- The layout should adapt responsively, ensuring no content is cut off on smaller screens.

### Add ScreenShots

- No footer
<img width="1279" alt="Screenshot 2024-10-20 at 2 17 28 PM" src="https://github.com/user-attachments/assets/eda8aad7-b822-4e42-8a17-8136fa290f8f">

- Overflown item

<img width="352" alt="Screenshot 2024-10-20 at 2 02 52 PM" src="https://github.com/user-attachments/assets/8647f41e-7a49-473e-9552-96cdcefaf3d1">

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by IkkiOcean** [comment]
Assign me this under GSSOC-ext and I assure you that PR in one day

**Comment by 4darsh-Dev** [comment]
assigned to you @IkkiOcean , 
Also make footer responsive properly

**Comment by 4darsh-Dev** [comment]
Hey @IkkiOcean ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
