### ISSUE TITLE
Adding FAQ page

### ISSUE THREAD

**Issue by AswaniBolisetti** [4darsh-Dev/DecenTrade#99]
@4darsh-Dev 
In FAQ page, no content added, i would like to work on it
could you please assign it to me

**Comment by 4darsh-Dev** [comment]
@AswaniBolisetti, 
There's already someone working on this issue, 
look for more issues.

**Comment by 4darsh-Dev** [comment]
Hey @AswaniBolisetti ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
